### ISSUE TITLE
EFS Mount Helper not supported on macOS Sonoma

### ISSUE THREAD

**Issue by sebskuse** [aws/efs-utils#191]
Hi,

We've recently updated to a macOS Sonoma-based AMI, and it appears that the helper doesn't yet support it. Attempting to mount gives the error:

> We do not support EFS on MacOS Kernel version 23.1.0
> mount: /Users/ec2-user/Dependencies failed with 1

Is there a timeline for Sonoma support?

**Comment by thimslugga** [comment]
This should be resolved by #195 and once the Homebrew tap is updated

**Comment by NorseGaud** [comment]
Just tried today with the latest brew and it's still throwing the failure with `amzn-ec2-macos-14.3-20240208-140501-arm64`

**Comment by NorseGaud** [comment]
@thimslugga , how do I build manually on macOS to get unblocked?

**Comment by anthotse** [comment]
Support for macOS Sonoma has been added.
